<?
  include("controller.php");
  include("model.php");
  include("xml_adapter.php");
  include(dirname(__FILE__)."/../app/controllers/offres_controller.php");
  include(dirname(__FILE__)."/../app/controllers/transactions_controller.php");
  include(dirname(__FILE__)."/../app/models/offres.php");
  include(dirname(__FILE__)."/../app/models/transactions.php");
?>
